Add API-X to vagrant install; Resolves https://github.com/Islandora-C…
Islandora-CLAW/claw_vagrant pull request #3
Opened 2017-01-24 15:02 UTC by ruebot

…LAW/CLAW/issues/504

See: https://github.com/Islandora-CLAW/CLAW/issues/504

# How to test:
* clone repo, and checkout issue-504 branch
* `vagrant up`
* You should have no errors in the build, and see something along the lines of:
```
==> default: Installing API-X
==> default: Installing API-X
==> default: 342 [sshd-SshClient[383534aa]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at /0.0.0.0:8101 presented unverified RSA key: 39:fa:f8:4a:db:36:59:a6:5b:8e:9a:a6:2d:b2:35:f7
==> default: Adding feature url mvn:org.fcrepo.apix/fcrepo-api-x-karaf/LATEST/xml/features
==> default: 
```

<hr />

I used `LATEST` instead of `0.1.0` because I got this error when installing with 0.1.0:

```
==> default: Adding feature url mvn:org.fcrepo.apix/fcrepo-api-x-karaf/0.1.0/xml/features
==> default: ERROR: Bundle org.fcrepo.camel.fcrepo-indexing-triplestore [118] EventDispatcher: Error during dispatch. (java.lang.IllegalAccessError: tried to access method org.fcrepo.client.FcrepoClient.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Boolean;)V from class org.fcrepo.camel.FcrepoProducer)
==> default: java.lang.IllegalAccessError: tried to access method org.fcrepo.client.FcrepoClient.<init>(Ljava/lang/String;Ljava/lang/String;L
==> default: java/lang/String;Ljava/lang/Boolean;)V from class org.fcrepo.camel.FcrepoProducer
==> default: 	at org.fcrepo.camel.FcrepoProducer.<init>(FcrepoProducer.java:73)
==> default: 	at org.fcrepo.camel.FcrepoEndpoint.createProducer(FcrepoEndpoint.java:73)
==> default: 	at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:439)
==> default: 	at org.apache.camel.impl.ProducerCache.acquireProducer(ProducerCache.java:160)
==> default: 	at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:243)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:79)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1372)
==> default: 	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:44)
==> default: 	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:31)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:156)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:62)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.MulticastProcessor.doStart(MulticastProcessor.java:1149)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:79)
==> default: 	at org.apache.camel.processor.FilterProcessor.doStart(FilterProcessor.java:116)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:79)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1372)
==> default: 	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:44)
==> default: 	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:31)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:156)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
==> default: 	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
==> default: 	at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:79)
==> default: 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
==> default: 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
==> default: 	at org.apache.camel.impl.RouteService.startChildService(RouteService.java:340)
==> default: 	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:182)
==> default: 	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3496)
==> default: 	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3426)
==> default: 	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3203)
==> default: 	at org.apac [...]

2017-01-24 21:43 UTC, dannylamb commented
@ruebot I think we need to update fcrepo-camel.  Which will require updating camel to 2.18.x.  This will also force us to upgrade the amherst services we have running as well.

That's an oversight on my part.

2017-01-24 21:45 UTC, dannylamb commented
@ruebot Are you ok with handling that explosion of scope?  We can address all those individually if you don't have the time right now.

2017-01-25 02:50 UTC, dannylamb commented
@ruebot https://github.com/Islandora-CLAW/claw_vagrant/blob/master/configs/karaf/fcrepo_camel_toolbox.script#L1

It's a transitive dependency of fcrepo-camel-toolbox.  Try bumping the version to 4.7.0.

You can update Amherst stuff here: https://github.com/Islandora-CLAW/claw_vagrant/blob/master/configs/karaf/islandora_id_mapping_service.script#L1

2017-01-25 20:19 UTC, dannylamb commented
@ruebot That sounds like a good course of action.

2017-01-27 20:27 UTC, dannylamb commented
@ruebot changes are looking good.  I'll spin up a copy as soon as I can and test.

2017-02-01 20:26 UTC, dannylamb requested changes
Something came up when working on https://github.com/Islandora-CLAW/Alpaca/pull/28.  The vagrant environment needs to be able to resolve Drupal urls, which we can't do at the moment because of our port forwarding strategy.  Can you please run apache on port 8000 so that localhost:8000 resolves on both guest and host machine?

2017-02-01 20:26 UTC, dannylamb commented on configs/karaf/fcrepo_camel_toolbox.script
> +feature:repo-add mvn:org.fcrepo.camel/toolbox-features/4.7.0/xml/features
If we install Alpaca first, we don't need these feature declarations.  Alpaca's features.xml will take care of it for us and you can delete these three lines.

2017-02-01 20:26 UTC, dannylamb commented on configs/karaf/islandora_id_mapping_service.script
>  feature:install acrepo-services-activemq
This has been replaced with fcrepo-service-activemq.  If this script gets run after alpaca, we'll be fine to delete this.

2017-02-02 13:06 UTC, dannylamb commented
`vagrant up`

2017-02-03 14:25 UTC, DiegoPino commented on configs/variables
> +GITHUB_TOKEN=f71459f666cabb3588d019b4d11e54e0befbda72
@ruebot are you giving your token away here?

2017-02-03 15:01 UTC, dannylamb approved these changes

2017-02-03 15:02 UTC, merged