504: Adding API-X to claw_vagrant
Islandora-CLAW/claw_vagrant pull request #40
Opened 2017-05-11 15:52 UTC by ajs6f

**Add API-X to vagrant install**: (https://github.com/Islandora-CLAW/CLAW/issues/504)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

https://github.com/fcrepo4-labs/fcrepo-api-x/pull/113
https://github.com/Islandora-CLAW/Alpaca/pull/40

# What does this Pull Request do?

Opens a port for API-X and adds a Syn-aware HTTP client feature supplied from the Alpaca PR linked above.

A brief description of what the intended result of the PR will be and/or what problem it solves.

After this PR and the ones above are merged and API-X has cut a release, API-X should come up in `claw_vagrant` out-of-the-box.

# How should this be tested?

Once all merges and releases have been accomplished, API-X should appear after the first `vagrant up` and should be available at mapped port 8081.

# Interested parties
@ruebot @dhlamb @birkland

2017-05-17 16:47 UTC, ajs6f commented
I believe this is now only waiting on https://github.com/Islandora-CLAW/Alpaca/pull/40 and an API-X release.

2017-05-17 18:37 UTC, birkland commented
@ajs6f I cut an 0.2.0 release last night.  Just confirmed that it has hit the shelves at Maven Central.

2017-05-17 18:38 UTC, ajs6f commented
Saw your new Maven badge-- cute! Thanks @birkland!

2017-05-24 12:23 UTC, dannylamb requested changes

2017-05-24 12:23 UTC, dannylamb commented on configs/karaf/alpaca.script
> +
Can you add a `feature:install fcrepo-api-x` in this script as well?

Also, can you bump the version number to 0.2.0 for the api-x feature?

2017-05-24 13:30 UTC, ajs6f commented on configs/karaf/alpaca.script
> +
Oh, duh, of course. Commit to follow.

2017-05-25 14:20 UTC, dannylamb commented
@ajs6f @birkland 

Just re-`vagrant up`'d and getting a lot of timeouts on the api-x bundle waiting for dependencies.  Here's the relevant bits from my log:

```
2017-05-25 14:06:18,977 | INFO  | nsole user karaf | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.7.1 | Bundle fcrepo-api-x-binding/0.2.0 is waiting for dependencies [(objectClass=org.fcrepo.apix.model.components.ExtensionRegistry), (&(org.fcrepo.apix.registry.role=default)(objectClass=org.fcrepo.apix.model.components.Registry)), (objectClass=org.fcrepo.apix.registry.HttpClientFetcher), (objectClass=org.fcrepo.apix.model.components.OntologyService)]
2017-05-25 14:06:20,958 | INFO  | nsole user karaf | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.7.1 | Bundle fcrepo-api-x-jena/0.2.0 is waiting for dependencies [(&(org.fcrepo.apix.registry.role=default)(objectClass=org.fcrepo.apix.model.components.Registry)), (objectClass=org.fcrepo.apix.registry.HttpClientFetcher)]
2017-05-25 14:06:29,574 | INFO  | nsole user karaf | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.7.1 | Bundle fcrepo-api-x-listener/0.2.0 is waiting for dependencies [(objectClass=org.fcrepo.apix.model.components.RoutingFactory)]
2017-05-25 14:06:31,666 | INFO  | nsole user karaf | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.7.1 | Bundle fcrepo-api-x-loader/0.2.0 is waiting for dependencies [(objectClass=org.fcrepo.apix.model.components.ExtensionRegistry), (&(org.fcrepo.apix.registry.role=default)(objectClass=org.fcrepo.apix.model.components.Registry)), (objectClass=org.fcrepo.apix.model.components.RoutingFactory), (objectClass=org.fcrepo.apix.model.components.ServiceRegistry)]
2017-05-25 14:06:37,674 | INFO  | nsole user karaf | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.7.1 | Bundle fcrepo-api-x-routing/0.2.0 is waiting for dependencies [(objectClass=org.fcrepo.apix.model.components.ExtensionRegistry), (objectClass=org.fcrepo.apix.model.components.Initializer), (objectClass=org.fcrepo.apix.model.components.ExtensionBinding), (objectClass=org.fcrepo.apix.model.components.ServiceRegistry)]
```

These were each followed by their corresponding timeout errors.  Restarting each bundle lead to the same errors.

It all seems to be internal dependencies within API-X.  I'm not sure what provides what under the hood, so I'm just reporting this back before digging any deeper.

2017-05-25 14:24 UTC, ajs6f commented
@dannylamb I've seen things like that before and the part that jumps out is 
```
Bundle fcrepo-api-x-jena/0.2.0 is waiting for dependencies [(&(org.fcrepo.apix.registry.role=default)(objectClass=org.fcrepo.apix.model.components.Registry)), (objectClass=org.fcrepo.apix.registry.HttpClientFetcher)]
```
because that may point to a problem getting at our special HTTP client (which is, of course, the whole dang point of this exercise).

2017-05-25 14:29 UTC, birkland commented
You know, I'm wondering if it's directly related to [fcrepo-api-x/#119](https://github.com/fcrepo4-labs/fcrepo-api-x/issues/119).  I haven't gotten back to that.  Could you try a workaround:  Add a file to karaf's `etc`: `org.fcrepo.apix.registry.http.cfg`, containing something trivial like:

    timeout.socket.ms = 1000

This just configures the default http client, which you'll be overriding anyway.   I suspect this is causing the `fcrepo-api-x-registry` bundle to fail to load, which is blocking everybody else.  If that's the case, I can dive into it this afternoon

2017-05-25 15:09 UTC, dannylamb commented
@birkland  

<img src="https://media.giphy.com/media/jir4LEGA68A9y/giphy.gif"/>

Adding the file as you instructed and restarting the bundles did the trick.  I can now reach Fedora through Api-X and am receiving its headers.

```
curl -I "http://localhost:8081/fcrepo/rest/"
HTTP/1.1 200 OK
Content-Type: text/rdf+n3
Accept: */*
Accept-Patch: application/sparql-update
Accept-Post: text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json,multipart/form-data,application/sparql-update
Allow: MOVE,COPY,DELETE,POST,HEAD,GET,PUT,PATCH,OPTIONS
Apix-Modality: intercept; outgoing
breadcrumbId: ID-claw-34458-1495714383208-7-8
ETag: W/"c989e64de3c261dfdf3d8188fc1096762690fbc6"
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Last-Modified: Thu, 25 May 2017 14:56:47 GMT
Link: <http://localhost:8081/discovery/>; rel="service"
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Server: Apache-Coyote/1.1
Content-Length: 0
```

@ajs6f Can you create that file [here](https://github.com/Islandora-CLAW/claw_vagrant/blob/master/scripts/islandora-karaf-components.sh#L13) before the script gets fed to Karaf as a workaround until @birkland more fully addresses the issue in Api-X?

2017-05-25 15:15 UTC, ajs6f commented
I can and will.

2017-05-25 18:18 UTC, ajs6f commented
@dannylamb That ^^^ is not _exactly_ the change you asked for, but it is substantively the same and I think it is actually a bit more karaf-idiomatic. Do you buy that? I can certainly do it the other way if you prefer.

2017-05-25 18:21 UTC, dannylamb commented
@ajs6f Oh cool, never thought of doing that.  That seems totally fine to me.  One last `vagrant up` and we'll finally have this.

2017-05-25 18:23 UTC, ajs6f commented
https://www.youtube.com/watch?v=NnP5iDKwuwk

2017-05-25 18:26 UTC, dannylamb commented
_summons his inner Jek Porkins_
I can hold it.

2017-05-25 19:58 UTC, dannylamb approved these changes

2017-05-25 20:00 UTC, dannylamb commented
After a fresh rebuild I can visit Fedora through the API-X proxy, am receiving the expected headers from GET/HEAD requests, and can see the service documents API-X bootstraps.

:shipit:

2017-05-25 20:00 UTC, ajs6f commented
https://www.youtube.com/watch?v=qniy8aDSFLA

2017-05-25 20:02 UTC, merged